#!/usr/bin/env bash
#  ██╗  ██╗██╗  ██╗██╗  ██╗███████╗███╗   ██╗ ██████╗ ███████╗
#  ╚██╗██╔╝╚██╗██╔╝██║  ██║██╔════╝████╗  ██║██╔═══██╗██╔════╝
#   ╚███╔╝  ╚███╔╝ ███████║█████╗  ██╔██╗ ██║██║   ██║███████╗
#   ██╔██╗  ██╔██╗ ╚════██║██╔══╝  ██║╚██╗██║██║   ██║╚════██║
#  ██╔╝ ██╗██╔╝ ██╗     ██║███████╗██║ ╚████║╚██████╔╝███████║
#  ╚═╝  ╚═╝╚═╝  ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝
#  Author  :  xxxenos
#  Based on:  https://github.com/gh0stzk/dotfiles
#  About   :  This file will configure and launch the rice.
#

# Set bspwm configuration for Xxxenos
set_bspwm_config() {
	bspc config border_width 3
	bspc config top_padding 48
	bspc config bottom_padding 2
	bspc config left_padding 2
	bspc config right_padding 2
	bspc config normal_border_color "#101010"
	bspc config active_border_color "#303030"
	bspc config focused_border_color "#505050"
	bspc config presel_feedback_color "#909090"
}

# Set alacritty colorscheme
set_alacritty_config() {
	cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (Xxxenos) Black and White color scheme

# Default colors
[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

# Cursor colors
[colors.cursor]
cursor = "#FFFFFF"
text = "#000000"

# Normal colors
[colors.normal]
black = "#101010"
blue = "#909090"
cyan = "#B0B0B0"
green = "#707070"
magenta = "#A0A0A0"
red = "#303030"
white = "#F0F0F0"
yellow = "#505050"

# Bright colors
[colors.bright]
black = "#202020"
blue = "#A0A0A0"
cyan = "#C0C0C0"
green = "#808080"
magenta = "#B0B0B0"
red = "#404040"
white = "#FFFFFF"
yellow = "#606060"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (Xxxenos) Black and White color scheme


# The basic colors
foreground              #FFFFFF
background              #000000
selection_foreground    #000000
selection_background    #FFFFFF

# Cursor colors
cursor                  #FFFFFF
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #B0B0B0

# Kitty window border colors
active_border_color     #A0A0A0
inactive_border_color   #202020
bell_border_color       #505050

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #FFFFFF
inactive_tab_foreground #FFFFFF
inactive_tab_background #303030
tab_bar_background      #000000

# The 16 terminal colors

# black
color0 #101010
color8 #202020

# red
color1 #303030
color9 #404040

# green
color2  #707070
color10 #808080

# yellow
color3  #505050
color11 #606060

# blue
color4  #909090
color12 #A0A0A0

# magenta
color5  #A0A0A0
color13 #B0B0B0

# cyan
color6  #B0B0B0
color14 #C0C0C0

# white
color7  #F0F0F0
color15 #FFFFFF
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = false; shadow = false; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 0/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"95:class_g = 'Alacritty'\"/g" \
		-e "s/\".*:class_g = 'kitty'\"/\"95:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"95:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 8/g" \
		-e "s/frame_color = .*/frame_color = \"#000000\"/g" \
		-e "s/separator_color = .*/separator_color = \"#303030\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#FFFFFF'/g"

	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#000000"
		foreground = "#FFFFFF"

		[urgency_normal]
		timeout = 6
		background = "#000000"
		foreground = "#FFFFFF"

		[urgency_critical]
		timeout = 0
		background = "#000000"
		foreground = "#FFFFFF"
	_EOF_
}

# Set eww colors
set_eww_colors() {
	cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for Xxxenos rice
\$bg: #000000;
\$bg-alt: #101010;
\$fg: #FFFFFF;
\$black: #202020;
\$lightblack: #303030;
\$red: #404040;
\$blue: #909090;
\$cyan: #B0B0B0;
\$magenta: #A0A0A0;
\$green: #707070;
\$yellow: #505050;
\$archicon: #A0A0A0;
EOF
}

# Set jgmenu colors for Xxxenos
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #000000/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #FFFFFF/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #303030/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #FFFFFF/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #505050/'
}

# Set Rofi launcher config
set_launcher_config() {
	sed -i "$HOME/.config/bspwm/scripts/Launcher.rasi" \
		-e '22s/\(font: \).*/\1"JetBrainsMono NF Bold 9";/' \
		-e 's/\(background: \).*/\1#000000F7;/' \
		-e 's/\(background-alt: \).*/\1#101010F5;/' \
		-e 's/\(foreground: \).*/\1#FFFFFF;/' \
		-e 's/\(selected: \).*/\1#909090;/' \
		-e "s/rices\/[[:alnum:]\-]*/rices\/${RICETHEME}/g"

	# NetworkManager launcher
	sed -i "$HOME/.config/bspwm/scripts/NetManagerDM.rasi" \
		-e '12s/\(background: \).*/\1#000000F7;/' \
		-e '13s/\(background-alt: \).*/\1#101010F5;/' \
		-e '14s/\(foreground: \).*/\1#FFFFFF;/' \
		-e '15s/\(selected: \).*/\1#909090;/' \
		-e '16s/\(active: \).*/\1#707070;/' \
		-e '17s/\(urgent: \).*/\1#404040;/'

	# WallSelect menu colors
	sed -i "$HOME/.config/bspwm/scripts/WallSelect.rasi" \
		-e 's/\(main-bg: \).*/\1#000000F7;/' \
		-e 's/\(main-fg: \).*/\1#FFFFFF;/' \
		-e 's/\(select-bg: \).*/\1#A0A0A0;/' \
		-e 's/\(select-fg: \).*/\1#000000;/'
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		(MONITOR=$mon polybar -q xxxenos-bar -c "${rice_dir}"/config.ini) &
		(MONITOR=$mon polybar -q xxxenos-bar2 -c "${rice_dir}"/config.ini) &
		(MONITOR=$mon polybar -q xxxenos-bar3 -c "${rice_dir}"/config.ini) &
	done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
launch_bars
set_dunst_config
set_eww_colors
set_jgmenu_colors
set_launcher_config 